import { linearView, moduleMeta, parseNumbers, snapshotFactory } from '../core/module-utils.js';

const common={category:'linear',categoryLabel:'线性结构',difficulty:'入门',minutes:7,quiz:{question:'这个结构中元素的访问顺序由什么决定？',options:['元素数值大小','结构的入口与出口规则','元素颜色'],answer:1}};

export const stack=moduleMeta({...common,id:'stack',title:'栈',file:'ArrayStack.java',renderer:'linear',description:'后进先出的入栈与出栈',objective:'理解 LIFO 和栈顶指针',inputLabel:'依次入栈的元素',defaultInput:'4, 7, 2, 9',complexity:'push/pop O(1)',code:['class Stack {','  int[] data; int top = -1;','  void push(int value) {','    data[++top] = value;','  }','  int pop() {','    return data[top--];','  }','}'],parseInput:raw=>parseNumbers(raw,{min:2,max:7}),run(input){const data=[],s=snapshotFactory(linearView(data,'stack'));let operations=0;s.ready('元素将依次入栈，最后再弹出栈顶元素。');input.forEach(value=>{data.push(value);operations++;s.emit('push',4,'入栈',`${value} 放到栈顶，下一个出栈的将是它。`,linearView(data,'stack',{active:[data.length-1],labels:{end:'栈顶'}}),{top:data.length-1,value},{operations,size:data.length});});const removed=data.pop();operations++;s.emit('pop',7,'出栈',`弹出栈顶 ${removed}，新的栈顶是 ${data.at(-1) ?? '空'}。`,linearView(data,'stack',{labels:{end:'栈顶'}}),{top:data.length-1,removed},{operations,size:data.length});s.emit('done',9,'演示完成',`完成 ${operations} 次操作，栈内剩余 ${data.length} 个元素。`,linearView(data,'stack',{completed:data.map((_,i)=>i),labels:{end:'栈顶'}}),{top:data.length-1},{operations,size:data.length});return s.steps;}});

export const queue=moduleMeta({...common,id:'queue',title:'队列',file:'ArrayQueue.java',renderer:'linear',description:'先进先出的入队与出队',objective:'理解 FIFO、队首和队尾',inputLabel:'依次入队的元素',defaultInput:'5, 2, 8, 4',complexity:'offer/poll O(1)',code:['class Queue {','  int head = 0, tail = 0;','  void offer(int value) {','    data[tail++] = value;','  }','  int poll() {','    return data[head++];','  }','}'],parseInput:raw=>parseNumbers(raw,{min:2,max:7}),run(input){const data=[],s=snapshotFactory(linearView(data,'queue'));let operations=0;s.ready('元素从队尾进入，从队首离开。');input.forEach(value=>{data.push(value);operations++;s.emit('enqueue',4,'入队',`${value} 加入队尾，队首仍是 ${data[0]}。`,linearView(data,'queue',{active:[data.length-1],labels:{start:'队首',end:'队尾'}}),{head:0,tail:data.length-1,value},{operations,size:data.length});});const removed=data.shift();operations++;s.emit('dequeue',7,'出队',`最早进入的 ${removed} 从队首离开。`,linearView(data,'queue',{active:[0],labels:{start:'队首',end:'队尾'}}),{head:0,tail:data.length-1,removed},{operations,size:data.length});s.emit('done',9,'演示完成',`队列保持先进先出，当前队首是 ${data[0]}。`,linearView(data,'queue',{completed:data.map((_,i)=>i),labels:{start:'队首',end:'队尾'}}),{head:0,tail:data.length-1},{operations,size:data.length});return s.steps;}});

export const linkedList=moduleMeta({...common,id:'singly-linked-list',title:'单链表',file:'LinkedList.java',renderer:'linear',description:'沿 next 引用访问、插入和删除节点',objective:'理解节点引用改变而非元素整体移动',inputLabel:'初始节点值',defaultInput:'3, 7, 5, 9',complexity:'访问 O(n)，头部修改 O(1)',code:['class Node { int value; Node next; }','Node insertAfter(Node node, int value) {','  Node added = new Node(value);','  added.next = node.next;','  node.next = added;','  return added;','}','void removeAfter(Node node) {','  node.next = node.next.next;','}'],parseInput:raw=>parseNumbers(raw,{min:3,max:6}),run(input){const values=[...input],s=snapshotFactory(linearView(values,'linked',{links:true}));let visits=0,updates=0;s.ready('从 head 沿 next 引用访问链表。');for(let i=0;i<values.length;i++){visits++;s.emit('visit',1,'访问节点',`沿 next 到达值为 ${values[i]} 的节点。`,linearView(values,'linked',{active:[i],links:true,labels:{start:'head'}}),{index:i,current:values[i]},{visits,updates});}const inserted=values[0]+1;values.splice(1,0,inserted);updates+=2;s.emit('insert',5,'插入节点',`新节点 ${inserted} 接到 head 之后，只修改两条 next 引用。`,linearView(values,'linked',{active:[0,1,2],links:true,labels:{start:'head'}}),{inserted},{visits,updates});const removed=values.splice(2,1)[0];updates++;s.emit('remove',9,'删除节点',`前驱节点跨过 ${removed} 指向下一节点，${removed} 脱离链表。`,linearView(values,'linked',{active:[1,2],links:true,labels:{start:'head'}}),{removed},{visits,updates});s.emit('done',10,'演示完成','链表操作通过改变引用完成，没有整体移动后续元素。',linearView(values,'linked',{completed:values.map((_,i)=>i),links:true,labels:{start:'head'}}),{head:values[0]},{visits,updates,size:values.length});return s.steps;}});
