import { moduleMeta, parseNumbers, snapshotFactory } from '../core/module-utils.js';

function treeNodesFromBst(root){const nodes=[],edges=[];function walk(n,depth=0,x=50,spread=24){if(!n)return;nodes.push({id:String(n.value),label:String(n.value),x,y:18+depth*24});if(n.left){edges.push([String(n.value),String(n.left.value)]);walk(n.left,depth+1,x-spread,Math.max(7,spread/2));}if(n.right){edges.push([String(n.value),String(n.right.value)]);walk(n.right,depth+1,x+spread,Math.max(7,spread/2));}}walk(root);return {kind:'tree',nodes,edges,active:[],completed:[]};}
function heapView(a,extra={}){const nodes=a.map((v,i)=>({id:String(i),label:String(v),x:i===0?50:(i===1?28:i===2?72: i<7 ? 14+(i-3)*24 : 10+i*8),y:18+Math.floor(Math.log2(i+1))*25}));const edges=a.slice(1).map((_,i)=>[String(Math.floor((i+1-1)/2)),String(i+1)]);return {kind:'tree',nodes,edges,active:[],completed:[],...extra};}
const treeCommon={category:'tree',categoryLabel:'树',renderer:'tree',quiz:{question:'树形结构中的访问路径由什么决定？',options:['节点在屏幕上的颜色','父子关系和算法规则','节点标签长度'],answer:1}};

export const binarySearchTree=moduleMeta({...treeCommon,id:'binary-search-tree',title:'二叉搜索树',file:'BinarySearchTree.java',description:'按大小关系搜索和插入节点',objective:'理解左小右大的有序关系',inputLabel:'依次插入的节点值',defaultInput:'8, 4, 12, 2, 6, 10, 14',complexity:'平均 O(log n)',minutes:8,code:['Node insert(Node root, int value) {','  if (root == null) return new Node(value);','  if (value < root.value)','    root.left = insert(root.left, value);','  else if (value > root.value)','    root.right = insert(root.right, value);','  return root;','}'],parseInput:raw=>parseNumbers(raw,{min:3,max:8}),run(input){let root=null;const empty={kind:'tree',nodes:[],edges:[],active:[],completed:[]},s=snapshotFactory(empty);let comparisons=0;s.ready('按输入顺序把节点插入二叉搜索树。');for(const value of input){if(!root){root={value,left:null,right:null};s.emit('insert',2,'创建根节点',`${value} 成为树的根节点。`,{...treeNodesFromBst(root),active:[String(value)]},{value},{comparisons,nodes:1});continue;}let cur=root;while(true){comparisons++;const view=treeNodesFromBst(root);view.active=[String(cur.value)];s.emit('compare',3,'比较节点',`${value} 与 ${cur.value} 比较，${value<cur.value?'向左':'向右'}继续。`,view,{value,current:cur.value},{comparisons,nodes:treeNodesFromBst(root).nodes.length});if(value===cur.value)break;const side=value<cur.value?'left':'right';if(!cur[side]){cur[side]={value,left:null,right:null};const inserted=treeNodesFromBst(root);inserted.active=[String(value)];s.emit('insert',side==='left'?4:6,'插入节点',`${value} 成为 ${cur.value} 的${side==='left'?'左':'右'}孩子。`,inserted,{value,parent:cur.value},{comparisons,nodes:inserted.nodes.length});break;}cur=cur[side];}}const view=treeNodesFromBst(root);view.completed=view.nodes.map(n=>n.id);s.emit('done',8,'构建完成','所有节点满足：左子树更小，右子树更大。',view,{root:root.value},{comparisons,nodes:view.nodes.length});return s.steps;}});

export const heap=moduleMeta({...treeCommon,id:'heap',title:'二叉堆',file:'MaxHeap.java',description:'通过上浮维护最大堆性质',objective:'理解完全二叉树与父子大小关系',inputLabel:'依次加入堆的元素',defaultInput:'4, 9, 3, 7, 8, 2',complexity:'插入 O(log n)',minutes:8,code:['void offer(int value) {','  heap.add(value);','  int i = heap.size() - 1;','  while (i > 0) {','    int parent = (i - 1) / 2;','    if (heap[parent] >= heap[i]) break;','    swap(heap, parent, i);','    i = parent;','  }','}'],parseInput:raw=>parseNumbers(raw,{min:3,max:8}),run(input){const a=[],s=snapshotFactory(heapView(a));let comparisons=0,swaps=0;s.ready('元素先加入完全二叉树末端，再向上调整。');for(const value of input){a.push(value);let i=a.length-1;s.emit('insert',2,'加入堆尾',`${value} 放到完全二叉树的下一个空位。`,heapView(a,{active:[String(i)]}),{i,value},{comparisons,swaps,size:a.length});while(i>0){const parent=Math.floor((i-1)/2);comparisons++;s.emit('compare',6,'比较父节点',`比较子节点 ${a[i]} 与父节点 ${a[parent]}。`,heapView(a,{active:[String(i),String(parent)]}),{i,parent},{comparisons,swaps,size:a.length});if(a[parent]>=a[i])break;[a[parent],a[i]]=[a[i],a[parent]];swaps++;s.emit('swap',7,'向上交换',`子节点更大，与父节点交换以恢复最大堆。`,heapView(a,{active:[String(i),String(parent)]}),{i,parent},{comparisons,swaps,size:a.length});i=parent;}}const view=heapView(a);view.completed=view.nodes.map(n=>n.id);s.emit('done',10,'最大堆完成',`根节点 ${a[0]} 是最大值，每个父节点都不小于孩子。`,view,{root:a[0]},{comparisons,swaps,size:a.length});return s.steps;}});

const graph={nodes:[{id:'A',x:16,y:50},{id:'B',x:36,y:20},{id:'C',x:36,y:78},{id:'D',x:64,y:18},{id:'E',x:64,y:52},{id:'F',x:84,y:76}],edges:[['A','B'],['A','C'],['B','D'],['B','E'],['C','E'],['D','F'],['E','F']]};
const adjacency={A:['B','C'],B:['A','D','E'],C:['A','E'],D:['B','F'],E:['B','C','F'],F:['D','E']};
const graphView=(extra={})=>({kind:'graph',nodes:graph.nodes,edges:graph.edges,active:[],completed:[],frontier:[],...extra});
function parseStart(raw){const start=String(raw).trim().toUpperCase();if(!adjacency[start])throw new Error('起点必须是 A、B、C、D、E 或 F');return start;}
const graphCommon={category:'graph',categoryLabel:'图',renderer:'graph',inputLabel:'起点（A-F）',defaultInput:'A',difficulty:'进阶',minutes:8,complexity:'O(V + E)',quiz:{question:'为什么图遍历需要记录 visited 集合？',options:['让节点颜色更丰富','避免环导致重复访问','自动给边排序'],answer:1}};

export const graphBfs=moduleMeta({...graphCommon,id:'graph-bfs',title:'广度优先搜索',file:'GraphBFS.java',description:'使用队列按层访问图',objective:'理解队列、层级访问和 visited 集合',code:['void bfs(Graph g, String start) {','  Queue<String> q = new ArrayDeque<>();','  Set<String> visited = new HashSet<>();','  q.offer(start); visited.add(start);','  while (!q.isEmpty()) {','    String node = q.poll();','    for (String next : g.neighbors(node))','      if (visited.add(next)) q.offer(next);','  }','}'],parseInput:parseStart,run(start){const s=snapshotFactory(graphView());const visited=new Set([start]),queue=[start],order=[];let edges=0;s.ready(`从 ${start} 开始，先加入队列。`);s.emit('enqueue',4,'起点入队',`${start} 标记为已发现并加入队列。`,graphView({active:[start],frontier:[...queue]}),{queue:queue.join(' → ')},{visits:0,edges});while(queue.length){const node=queue.shift();order.push(node);s.emit('visit',6,'访问队首',`${node} 从队首取出，按层检查它的邻居。`,graphView({active:[node],completed:[...order],frontier:[...queue]}),{node,queue:queue.join(' → ')||'空'},{visits:order.length,edges});for(const next of adjacency[node]){edges++;if(!visited.has(next)){visited.add(next);queue.push(next);s.emit('enqueue',8,'发现新节点',`${next} 首次被发现，加入队尾等待访问。`,graphView({active:[node,next],completed:[...order],frontier:[...queue]}),{node,next,queue:queue.join(' → ')},{visits:order.length,edges});}}}s.emit('done',10,'遍历完成',`BFS 访问顺序：${order.join(' → ')}。`,graphView({completed:[...order]}),{order:order.join(' → ')},{visits:order.length,edges});return s.steps;}});

export const graphDfs=moduleMeta({...graphCommon,id:'graph-dfs',title:'深度优先搜索',file:'GraphDFS.java',description:'沿一条路径深入，再回溯',objective:'理解递归栈、深入与回溯',code:['void dfs(Graph g, String node, Set<String> visited) {','  visited.add(node);','  for (String next : g.neighbors(node)) {','    if (!visited.contains(next))','      dfs(g, next, visited);','  }','}'],parseInput:parseStart,run(start){const s=snapshotFactory(graphView()),visited=new Set(),order=[];let edges=0;s.ready(`从 ${start} 开始沿一条路径尽量深入。`);function dfs(node,stack){visited.add(node);order.push(node);s.emit('visit',2,'深入访问',`${node} 加入 visited，递归栈为 ${[...stack,node].join(' → ')}。`,graphView({active:[node],completed:[...order],frontier:[...stack,node]}),{node,stack:[...stack,node].join(' → ')},{visits:order.length,edges});for(const next of adjacency[node]){edges++;if(!visited.has(next))dfs(next,[...stack,node]);}s.emit('backtrack',6,'回溯',`${node} 的未访问邻居已处理，返回上一层。`,graphView({active:[node],completed:[...order],frontier:[...stack]}),{node,stack:stack.join(' → ')||'空'},{visits:order.length,edges});}dfs(start,[]);s.emit('done',7,'遍历完成',`DFS 访问顺序：${order.join(' → ')}。`,graphView({completed:[...order]}),{order:order.join(' → ')},{visits:order.length,edges});return s.steps;}});
