import { DEFAULT_DELAY, PlaybackEngine } from './core/engine.js';
import { categories, moduleMap, modules } from './modules/registry.js';

const app=document.querySelector('#app');
const progress=document.querySelector('#catalogProgress');
const engine=new PlaybackEngine(()=>renderStep());
let currentModule=null,currentInput=null,filter='all',query='';
const pageParams=new URLSearchParams(location.search);
if(pageParams.get('theme')==='dark'||(!pageParams.has('theme')&&localStorage.getItem('algolab-theme')==='dark'))document.body.classList.add('dark');
if(pageParams.get('focus')==='1')document.body.classList.add('focus-mode');
progress.textContent=`${modules.filter(m=>m.status==='complete').length} / ${modules.length} 已完成`;

const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function route(){engine.stop();const parts=location.hash.replace(/^#\/?/,'').split('/');if(parts[0]==='lab'&&moduleMap.has(parts[1]))showLab(moduleMap.get(parts[1]));else showCatalog();window.scrollTo(0,0);app.focus();}

function showCatalog(){currentModule=null;document.title='算法总览 - AlgoLab';const complete=modules.filter(m=>m.status==='complete').length;app.innerHTML=`
  <section class="catalog-head"><div><span class="kicker">JAVA ALGORITHM LAB</span><h1>算法与数据结构实验室</h1><p>选择一个主题，在代码、状态和解释同步变化的过程中理解算法。</p></div><div class="catalog-stat"><strong>${modules.length}</strong><span>核心模块</span><b>${complete} 已通过验收</b></div></section>
  <section class="catalog-tools"><div class="filters" id="filters">${categories.map(c=>`<button class="filter ${c.id===filter?'active':''}" data-filter="${c.id}">${c.label}<span>${c.id==='all'?modules.length:modules.filter(m=>m.category===c.id).length}</span></button>`).join('')}</div><label class="search"><span>⌕</span><input id="searchInput" type="search" placeholder="搜索算法或数据结构" value="${escapeHtml(query)}"></label></section>
  <section class="module-grid" id="moduleGrid"></section>`;
  document.querySelector('#filters').addEventListener('click',e=>{const button=e.target.closest('[data-filter]');if(!button)return;filter=button.dataset.filter;showCatalog();});
  document.querySelector('#searchInput').addEventListener('input',e=>{query=e.target.value;renderCards();});renderCards();}

function renderCards(){const grid=document.querySelector('#moduleGrid');if(!grid)return;const term=query.trim().toLowerCase();const shown=modules.filter(m=>(filter==='all'||m.category===filter)&&(!term||`${m.title}${m.description}${m.id}`.toLowerCase().includes(term)));grid.innerHTML=shown.length?shown.map((m,index)=>`
  <article class="module-card"><div class="card-top"><span class="module-no">${String(modules.indexOf(m)+1).padStart(2,'0')}</span><span class="category-tag">${m.categoryLabel}</span><span class="verified ${m.status}">${m.status==='complete'?'✓ 已验收':'◌ 验收中'}</span></div><h2>${m.title}</h2><p>${m.description}</p><div class="card-meta"><span>${m.difficulty}</span><span>${m.minutes} 分钟</span><span>${m.complexity}</span></div><a class="enter-link" href="#/lab/${m.id}" target="_blank" rel="noopener">进入实验室 <span>→</span></a></article>`).join(''):`<div class="empty">没有匹配的模块</div>`;}

function showLab(module){currentModule=module;document.title=`${module.title} - AlgoLab`;app.innerHTML=`
  <section class="lesson-head"><div><a href="#/catalog" class="back-link">← 算法总览</a><div class="crumb">${module.categoryLabel} / ${module.difficulty}</div><h1>${module.title}</h1><p>${module.objective}</p></div><div class="lesson-meta"><span>${module.minutes} 分钟</span><strong>${module.complexity}</strong><button class="outline-btn" id="focusButton">演示模式</button></div></section>
  <section class="workspace">
    <aside class="code-panel"><div class="panel-head"><span class="file-tab"><b>J</b>${module.file}</span><span class="compiled">● 已编译</span></div><div class="code" id="codeBlock"></div><div class="variables"><span class="label">当前变量</span><div id="variableGrid" class="variable-grid"></div></div></aside>
    <section class="visual-panel"><div class="visual-head"><div><span class="kicker">运行画布</span><h2>${module.title}状态</h2></div><div class="legend"><span><i class="swatch active"></i>当前</span><span><i class="swatch done"></i>已完成</span><span><i class="swatch excluded"></i>已排除</span></div></div><div class="stage" id="stage"></div><div class="explanation" aria-live="polite"><span class="explain-icon">→</span><div><strong id="stepTitle">准备开始</strong><p id="stepText"></p></div><span id="stepCount">0 / 0</span></div><div class="metrics" id="metrics"></div></section>
  </section>
  <section class="control-deck"><div class="input-side"><label for="moduleInput">${module.inputLabel}</label><input id="moduleInput" value="${escapeHtml(module.defaultInput)}"><button class="primary-btn" id="applyButton">应用并重置</button><button class="icon-btn" id="randomButton" title="随机输入" aria-label="随机生成输入">↻</button><span class="input-error" id="inputError"></span></div><div class="playback"><button class="icon-btn" id="resetButton" title="回到开始" aria-label="回到开始">↤</button><button class="icon-btn" id="prevButton" title="上一步" aria-label="上一步">‹</button><button class="play-btn" id="playButton" aria-label="播放">▶</button><button class="icon-btn" id="nextButton" title="下一步" aria-label="下一步">›</button><label class="speed">速度<input id="speedRange" type="range" min="400" max="4000" value="${DEFAULT_DELAY}" step="200"><b id="speedLabel">1.0×</b></label></div></section>
  <section class="quiz-band"><div><span class="kicker">理解检测</span><h2>${module.quiz.question}</h2><p>选择答案，立即验证你对当前结构的理解。</p></div><div class="quiz" id="quiz">${module.quiz.options.map((option,i)=>`<button data-answer="${i}"><b>${String.fromCharCode(65+i)}</b>${option}</button>`).join('')}<p id="quizFeedback"></p></div></section>`;
  document.querySelector('#codeBlock').innerHTML=module.code.map((line,i)=>`<div class="code-line" data-line="${i+1}"><span>${i+1}</span><code>${highlight(line)}</code></div>`).join('');bindLab();loadInput(module.defaultInput);}

function highlight(line){return escapeHtml(line).replace(/\b(static|void|int|class|return|for|while|if|else|new)\b/g,'<em>$1</em>').replace(/\b(true|false|null)\b/g,'<mark>$1</mark>');}
function loadInput(raw){try{currentInput=currentModule.parseInput(raw);engine.load(currentModule.run(currentInput));document.querySelector('#inputError').textContent='';document.querySelector('#moduleInput').classList.remove('invalid');}catch(error){document.querySelector('#inputError').textContent=error.message;document.querySelector('#moduleInput').classList.add('invalid');}}
function bindLab(){
  const $=id=>document.querySelector(`#${id}`);$('applyButton').onclick=()=>loadInput($('moduleInput').value);$('moduleInput').onkeydown=e=>{if(e.key==='Enter')loadInput(e.target.value);};$('randomButton').onclick=()=>{const value=randomInput(currentModule);$('moduleInput').value=value;loadInput(value);};$('playButton').onclick=()=>engine.play();$('prevButton').onclick=()=>engine.move(-1);$('nextButton').onclick=()=>engine.move(1);$('resetButton').onclick=()=>engine.reset();$('speedRange').oninput=e=>{const v=Number(e.target.value);$('speedLabel').textContent=`${(DEFAULT_DELAY/v).toFixed(1)}×`;engine.setDelay(v);};$('focusButton').onclick=()=>document.body.classList.toggle('focus-mode');$('quiz').onclick=e=>{const b=e.target.closest('[data-answer]');if(!b)return;document.querySelectorAll('[data-answer]').forEach(x=>x.classList.remove('correct','wrong'));const ok=Number(b.dataset.answer)===currentModule.quiz.answer;b.classList.add(ok?'correct':'wrong');$('quizFeedback').textContent=ok?'回答正确，你已经抓住了这个模块的关键不变量。':'再观察关键步骤，留意状态改变的原因。';};}
function randomInput(module){if(module.category==='graph')return ['A','B','C','D','E','F'][Math.floor(Math.random()*6)];const nums=Array.from({length:6},()=>Math.floor(Math.random()*19)+1);if(module.id==='binary-search')nums.sort((a,b)=>a-b);if(module.category==='searching')return `${nums.join(', ')} | ${nums[Math.floor(Math.random()*nums.length)]}`;return nums.join(', ');}

function renderStep(){if(!currentModule||!engine.current)return;const step=engine.current;renderView(step.view);document.querySelectorAll('.code-line').forEach(line=>line.classList.toggle('current',Number(line.dataset.line)===step.line));document.querySelector('#stepTitle').textContent=step.title;document.querySelector('#stepText').textContent=step.text;document.querySelector('#stepCount').textContent=`${engine.cursor} / ${engine.steps.length-1}`;document.querySelector('#playButton').textContent=engine.timer?'Ⅱ':'▶';document.querySelector('#playButton').setAttribute('aria-label',engine.timer?'暂停':'播放');document.querySelector('#prevButton').disabled=engine.cursor===0;document.querySelector('#nextButton').disabled=engine.cursor===engine.steps.length-1;document.querySelector('#variableGrid').innerHTML=Object.entries(step.variables).slice(0,6).map(([k,v])=>`<div><span>${escapeHtml(k)}</span><strong>${escapeHtml(v)}</strong></div>`).join('')||'<div><span>状态</span><strong>—</strong></div>';document.querySelector('#metrics').innerHTML=Object.entries(step.metrics).slice(0,4).map(([k,v])=>`<div><span>${metricLabel(k)}</span><strong>${escapeHtml(v)}</strong></div>`).join('')+`<div><span>复杂度</span><strong>${currentModule.complexity}</strong></div>`;}
const metricLabel=k=>({comparisons:'比较次数',swaps:'交换次数',writes:'写入次数',visits:'访问次数',operations:'操作次数',size:'元素数量',nodes:'节点数量',edges:'边检查次数',updates:'引用更新',result:'结果'}[k]||k);

function renderView(view){const stage=document.querySelector('#stage');if(view.kind==='array')stage.innerHTML=renderArray(view);else if(view.kind==='linear')stage.innerHTML=renderLinear(view);else stage.innerHTML=renderSvg(view);}
function renderArray(v){const max=Math.max(...v.values,1);return `<div class="array-canvas"><div class="array-bars">${v.values.map((value,i)=>`<div class="bar-wrap"><div class="bar ${stateClass(v,i)}" style="height:${Math.max(22,value/max*100)}%"><b>${value}</b><small>${v.active.includes(i)?'当前':v.completed.includes(i)?'完成':v.excluded.includes(i)?'排除':''}</small></div><span>[${i}]</span></div>`).join('')}</div></div>`;}
function stateClass(v,i){return v.active?.includes(i)?'is-active':v.completed?.includes(i)?'is-done':v.excluded?.includes(i)?'is-excluded':'';}
function renderLinear(v){const arrow=v.links?'next →':'→';return `<div class="linear-canvas ${v.mode}">${v.labels?.start?`<span class="end-label">${v.labels.start}</span>`:''}${v.values.map((value,i)=>`<div class="linear-node ${stateClass(v,i)}"><b>${value}</b><small>${v.active.includes(i)?'当前':v.completed?.includes(i)?'完成':''}</small></div>${i<v.values.length-1?`<span class="link">${arrow}</span>`:''}`).join('')}${v.labels?.end?`<span class="end-label">${v.labels.end}</span>`:''}${!v.values.length?'<span class="empty-state">结构为空</span>':''}</div>`;}
function renderSvg(v){if(!v.nodes.length)return `<div class="pending-view"><b>节点序列已就绪</b><span>点击播放后按输入顺序构建结构</span></div>`;const nodeMap=new Map(v.nodes.map(n=>[n.id,n]));return `<svg class="diagram" viewBox="0 0 100 100" role="img" aria-label="${v.kind==='graph'?'图遍历':'树结构'}状态">${v.edges.map(([a,b])=>{const x=nodeMap.get(a),y=nodeMap.get(b);return `<line x1="${x.x}" y1="${x.y}" x2="${y.x}" y2="${y.y}"/>`;}).join('')}${v.nodes.map(n=>`<g class="diagram-node ${v.active.includes(n.id)?'is-active':v.completed.includes(n.id)?'is-done':v.frontier?.includes(n.id)?'is-frontier':''}"><circle cx="${n.x}" cy="${n.y}" r="5.8"/><text x="${n.x}" y="${n.y+.8}">${escapeHtml(n.label??n.id)}</text></g>`).join('')}</svg>`;}

document.querySelector('#themeButton').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('algolab-theme',document.body.classList.contains('dark')?'dark':'light');};window.addEventListener('hashchange',route);document.addEventListener('keydown',e=>{if(!currentModule||['INPUT','BUTTON'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();engine.play();}if(e.key==='ArrowRight')engine.move(1);if(e.key==='ArrowLeft')engine.move(-1);});route();
